/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.TextualSlcoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextualSlcoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextualSlcoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextualSlcoActivator.getInstance().getInjector(TextualSlcoActivator.ORG_XTEXT_TEXTUALSLCO);
	}
	
}
