/**
 */
package promela.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import promela.util.PromelaAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PromelaItemProviderAdapterFactory extends PromelaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PromelaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.spec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected specItemProvider specItemProvider;

	/**
	 * This creates an adapter for a {@link promela.spec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createspecAdapter() {
		if (specItemProvider == null) {
			specItemProvider = new specItemProvider(this);
		}

		return specItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.proctype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected proctypeItemProvider proctypeItemProvider;

	/**
	 * This creates an adapter for a {@link promela.proctype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createproctypeAdapter() {
		if (proctypeItemProvider == null) {
			proctypeItemProvider = new proctypeItemProvider(this);
		}

		return proctypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.init} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected initItemProvider initItemProvider;

	/**
	 * This creates an adapter for a {@link promela.init}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createinitAdapter() {
		if (initItemProvider == null) {
			initItemProvider = new initItemProvider(this);
		}

		return initItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.never} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected neverItemProvider neverItemProvider;

	/**
	 * This creates an adapter for a {@link promela.never}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createneverAdapter() {
		if (neverItemProvider == null) {
			neverItemProvider = new neverItemProvider(this);
		}

		return neverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.trace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected traceItemProvider traceItemProvider;

	/**
	 * This creates an adapter for a {@link promela.trace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtraceAdapter() {
		if (traceItemProvider == null) {
			traceItemProvider = new traceItemProvider(this);
		}

		return traceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.utype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected utypeItemProvider utypeItemProvider;

	/**
	 * This creates an adapter for a {@link promela.utype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createutypeAdapter() {
		if (utypeItemProvider == null) {
			utypeItemProvider = new utypeItemProvider(this);
		}

		return utypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.mtype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected mtypeItemProvider mtypeItemProvider;

	/**
	 * This creates an adapter for a {@link promela.mtype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createmtypeAdapter() {
		if (mtypeItemProvider == null) {
			mtypeItemProvider = new mtypeItemProvider(this);
		}

		return mtypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.one_decl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected one_declItemProvider one_declItemProvider;

	/**
	 * This creates an adapter for a {@link promela.one_decl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createone_declAdapter() {
		if (one_declItemProvider == null) {
			one_declItemProvider = new one_declItemProvider(this);
		}

		return one_declItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.primitivetype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected primitivetypeItemProvider primitivetypeItemProvider;

	/**
	 * This creates an adapter for a {@link promela.primitivetype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createprimitivetypeAdapter() {
		if (primitivetypeItemProvider == null) {
			primitivetypeItemProvider = new primitivetypeItemProvider(this);
		}

		return primitivetypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.uname} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected unameItemProvider unameItemProvider;

	/**
	 * This creates an adapter for a {@link promela.uname}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createunameAdapter() {
		if (unameItemProvider == null) {
			unameItemProvider = new unameItemProvider(this);
		}

		return unameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.chanassert} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected chanassertItemProvider chanassertItemProvider;

	/**
	 * This creates an adapter for a {@link promela.chanassert}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createchanassertAdapter() {
		if (chanassertItemProvider == null) {
			chanassertItemProvider = new chanassertItemProvider(this);
		}

		return chanassertItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.ivar} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ivarItemProvider ivarItemProvider;

	/**
	 * This creates an adapter for a {@link promela.ivar}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createivarAdapter() {
		if (ivarItemProvider == null) {
			ivarItemProvider = new ivarItemProvider(this);
		}

		return ivarItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.ch_init} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ch_initItemProvider ch_initItemProvider;

	/**
	 * This creates an adapter for a {@link promela.ch_init}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createch_initAdapter() {
		if (ch_initItemProvider == null) {
			ch_initItemProvider = new ch_initItemProvider(this);
		}

		return ch_initItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.varref} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected varrefItemProvider varrefItemProvider;

	/**
	 * This creates an adapter for a {@link promela.varref}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createvarrefAdapter() {
		if (varrefItemProvider == null) {
			varrefItemProvider = new varrefItemProvider(this);
		}

		return varrefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.send} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected sendItemProvider sendItemProvider;

	/**
	 * This creates an adapter for a {@link promela.send}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createsendAdapter() {
		if (sendItemProvider == null) {
			sendItemProvider = new sendItemProvider(this);
		}

		return sendItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.receive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected receiveItemProvider receiveItemProvider;

	/**
	 * This creates an adapter for a {@link promela.receive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createreceiveAdapter() {
		if (receiveItemProvider == null) {
			receiveItemProvider = new receiveItemProvider(this);
		}

		return receiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.recv_arg_varref} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected recv_arg_varrefItemProvider recv_arg_varrefItemProvider;

	/**
	 * This creates an adapter for a {@link promela.recv_arg_varref}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createrecv_arg_varrefAdapter() {
		if (recv_arg_varrefItemProvider == null) {
			recv_arg_varrefItemProvider = new recv_arg_varrefItemProvider(this);
		}

		return recv_arg_varrefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.recv_arg_eval_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected recv_arg_eval_exprItemProvider recv_arg_eval_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.recv_arg_eval_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createrecv_arg_eval_exprAdapter() {
		if (recv_arg_eval_exprItemProvider == null) {
			recv_arg_eval_exprItemProvider = new recv_arg_eval_exprItemProvider(this);
		}

		return recv_arg_eval_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.assign_std} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected assign_stdItemProvider assign_stdItemProvider;

	/**
	 * This creates an adapter for a {@link promela.assign_std}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createassign_stdAdapter() {
		if (assign_stdItemProvider == null) {
			assign_stdItemProvider = new assign_stdItemProvider(this);
		}

		return assign_stdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.assign_inc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected assign_incItemProvider assign_incItemProvider;

	/**
	 * This creates an adapter for a {@link promela.assign_inc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createassign_incAdapter() {
		if (assign_incItemProvider == null) {
			assign_incItemProvider = new assign_incItemProvider(this);
		}

		return assign_incItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.assign_dec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected assign_decItemProvider assign_decItemProvider;

	/**
	 * This creates an adapter for a {@link promela.assign_dec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createassign_decAdapter() {
		if (assign_decItemProvider == null) {
			assign_decItemProvider = new assign_decItemProvider(this);
		}

		return assign_decItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.if_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected if_stmntItemProvider if_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.if_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createif_stmntAdapter() {
		if (if_stmntItemProvider == null) {
			if_stmntItemProvider = new if_stmntItemProvider(this);
		}

		return if_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.do_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected do_stmntItemProvider do_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.do_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createdo_stmntAdapter() {
		if (do_stmntItemProvider == null) {
			do_stmntItemProvider = new do_stmntItemProvider(this);
		}

		return do_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.atomic_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected atomic_stmntItemProvider atomic_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.atomic_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createatomic_stmntAdapter() {
		if (atomic_stmntItemProvider == null) {
			atomic_stmntItemProvider = new atomic_stmntItemProvider(this);
		}

		return atomic_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.d_step_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected d_step_stmntItemProvider d_step_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.d_step_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter created_step_stmntAdapter() {
		if (d_step_stmntItemProvider == null) {
			d_step_stmntItemProvider = new d_step_stmntItemProvider(this);
		}

		return d_step_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.block_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected block_stmntItemProvider block_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.block_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createblock_stmntAdapter() {
		if (block_stmntItemProvider == null) {
			block_stmntItemProvider = new block_stmntItemProvider(this);
		}

		return block_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.else_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected else_stmntItemProvider else_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.else_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createelse_stmntAdapter() {
		if (else_stmntItemProvider == null) {
			else_stmntItemProvider = new else_stmntItemProvider(this);
		}

		return else_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.break_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected break_stmntItemProvider break_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.break_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createbreak_stmntAdapter() {
		if (break_stmntItemProvider == null) {
			break_stmntItemProvider = new break_stmntItemProvider(this);
		}

		return break_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.goto_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected goto_stmntItemProvider goto_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.goto_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter creategoto_stmntAdapter() {
		if (goto_stmntItemProvider == null) {
			goto_stmntItemProvider = new goto_stmntItemProvider(this);
		}

		return goto_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.print_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected print_stmntItemProvider print_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.print_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createprint_stmntAdapter() {
		if (print_stmntItemProvider == null) {
			print_stmntItemProvider = new print_stmntItemProvider(this);
		}

		return print_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.assert_stmnt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected assert_stmntItemProvider assert_stmntItemProvider;

	/**
	 * This creates an adapter for a {@link promela.assert_stmnt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createassert_stmntAdapter() {
		if (assert_stmntItemProvider == null) {
			assert_stmntItemProvider = new assert_stmntItemProvider(this);
		}

		return assert_stmntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.c_code} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected c_codeItemProvider c_codeItemProvider;

	/**
	 * This creates an adapter for a {@link promela.c_code}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createc_codeAdapter() {
		if (c_codeItemProvider == null) {
			c_codeItemProvider = new c_codeItemProvider(this);
		}

		return c_codeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.c_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected c_exprItemProvider c_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.c_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createc_exprAdapter() {
		if (c_exprItemProvider == null) {
			c_exprItemProvider = new c_exprItemProvider(this);
		}

		return c_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.c_decl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected c_declItemProvider c_declItemProvider;

	/**
	 * This creates an adapter for a {@link promela.c_decl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createc_declAdapter() {
		if (c_declItemProvider == null) {
			c_declItemProvider = new c_declItemProvider(this);
		}

		return c_declItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.c_track} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected c_trackItemProvider c_trackItemProvider;

	/**
	 * This creates an adapter for a {@link promela.c_track}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createc_trackAdapter() {
		if (c_trackItemProvider == null) {
			c_trackItemProvider = new c_trackItemProvider(this);
		}

		return c_trackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.c_state} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected c_stateItemProvider c_stateItemProvider;

	/**
	 * This creates an adapter for a {@link promela.c_state}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createc_stateAdapter() {
		if (c_stateItemProvider == null) {
			c_stateItemProvider = new c_stateItemProvider(this);
		}

		return c_stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.options} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected optionsItemProvider optionsItemProvider;

	/**
	 * This creates an adapter for a {@link promela.options}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createoptionsAdapter() {
		if (optionsItemProvider == null) {
			optionsItemProvider = new optionsItemProvider(this);
		}

		return optionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.bin_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected bin_exprItemProvider bin_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.bin_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createbin_exprAdapter() {
		if (bin_exprItemProvider == null) {
			bin_exprItemProvider = new bin_exprItemProvider(this);
		}

		return bin_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.un_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected un_exprItemProvider un_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.un_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createun_exprAdapter() {
		if (un_exprItemProvider == null) {
			un_exprItemProvider = new un_exprItemProvider(this);
		}

		return un_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.cond_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected cond_exprItemProvider cond_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.cond_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createcond_exprAdapter() {
		if (cond_exprItemProvider == null) {
			cond_exprItemProvider = new cond_exprItemProvider(this);
		}

		return cond_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.len_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected len_exprItemProvider len_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.len_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createlen_exprAdapter() {
		if (len_exprItemProvider == null) {
			len_exprItemProvider = new len_exprItemProvider(this);
		}

		return len_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.timeout_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected timeout_exprItemProvider timeout_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.timeout_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtimeout_exprAdapter() {
		if (timeout_exprItemProvider == null) {
			timeout_exprItemProvider = new timeout_exprItemProvider(this);
		}

		return timeout_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.np__expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected np__exprItemProvider np__exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.np__expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createnp__exprAdapter() {
		if (np__exprItemProvider == null) {
			np__exprItemProvider = new np__exprItemProvider(this);
		}

		return np__exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.enabled_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected enabled_exprItemProvider enabled_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.enabled_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createenabled_exprAdapter() {
		if (enabled_exprItemProvider == null) {
			enabled_exprItemProvider = new enabled_exprItemProvider(this);
		}

		return enabled_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.pc_value_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected pc_value_exprItemProvider pc_value_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.pc_value_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createpc_value_exprAdapter() {
		if (pc_value_exprItemProvider == null) {
			pc_value_exprItemProvider = new pc_value_exprItemProvider(this);
		}

		return pc_value_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.name_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected name_exprItemProvider name_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.name_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createname_exprAdapter() {
		if (name_exprItemProvider == null) {
			name_exprItemProvider = new name_exprItemProvider(this);
		}

		return name_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.run_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected run_exprItemProvider run_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.run_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createrun_exprAdapter() {
		if (run_exprItemProvider == null) {
			run_exprItemProvider = new run_exprItemProvider(this);
		}

		return run_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.andor_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected andor_exprItemProvider andor_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.andor_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createandor_exprAdapter() {
		if (andor_exprItemProvider == null) {
			andor_exprItemProvider = new andor_exprItemProvider(this);
		}

		return andor_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.chanpoll_expr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected chanpoll_exprItemProvider chanpoll_exprItemProvider;

	/**
	 * This creates an adapter for a {@link promela.chanpoll_expr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createchanpoll_exprAdapter() {
		if (chanpoll_exprItemProvider == null) {
			chanpoll_exprItemProvider = new chanpoll_exprItemProvider(this);
		}

		return chanpoll_exprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.num_const} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected num_constItemProvider num_constItemProvider;

	/**
	 * This creates an adapter for a {@link promela.num_const}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createnum_constAdapter() {
		if (num_constItemProvider == null) {
			num_constItemProvider = new num_constItemProvider(this);
		}

		return num_constItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.enum_const} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected enum_constItemProvider enum_constItemProvider;

	/**
	 * This creates an adapter for a {@link promela.enum_const}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createenum_constAdapter() {
		if (enum_constItemProvider == null) {
			enum_constItemProvider = new enum_constItemProvider(this);
		}

		return enum_constItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link promela.mtype_const} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected mtype_constItemProvider mtype_constItemProvider;

	/**
	 * This creates an adapter for a {@link promela.mtype_const}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createmtype_constAdapter() {
		if (mtype_constItemProvider == null) {
			mtype_constItemProvider = new mtype_constItemProvider(this);
		}

		return mtype_constItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (specItemProvider != null) specItemProvider.dispose();
		if (proctypeItemProvider != null) proctypeItemProvider.dispose();
		if (initItemProvider != null) initItemProvider.dispose();
		if (neverItemProvider != null) neverItemProvider.dispose();
		if (traceItemProvider != null) traceItemProvider.dispose();
		if (utypeItemProvider != null) utypeItemProvider.dispose();
		if (mtypeItemProvider != null) mtypeItemProvider.dispose();
		if (one_declItemProvider != null) one_declItemProvider.dispose();
		if (primitivetypeItemProvider != null) primitivetypeItemProvider.dispose();
		if (unameItemProvider != null) unameItemProvider.dispose();
		if (chanassertItemProvider != null) chanassertItemProvider.dispose();
		if (ivarItemProvider != null) ivarItemProvider.dispose();
		if (ch_initItemProvider != null) ch_initItemProvider.dispose();
		if (varrefItemProvider != null) varrefItemProvider.dispose();
		if (sendItemProvider != null) sendItemProvider.dispose();
		if (receiveItemProvider != null) receiveItemProvider.dispose();
		if (recv_arg_varrefItemProvider != null) recv_arg_varrefItemProvider.dispose();
		if (recv_arg_eval_exprItemProvider != null) recv_arg_eval_exprItemProvider.dispose();
		if (assign_stdItemProvider != null) assign_stdItemProvider.dispose();
		if (assign_incItemProvider != null) assign_incItemProvider.dispose();
		if (assign_decItemProvider != null) assign_decItemProvider.dispose();
		if (if_stmntItemProvider != null) if_stmntItemProvider.dispose();
		if (do_stmntItemProvider != null) do_stmntItemProvider.dispose();
		if (atomic_stmntItemProvider != null) atomic_stmntItemProvider.dispose();
		if (d_step_stmntItemProvider != null) d_step_stmntItemProvider.dispose();
		if (block_stmntItemProvider != null) block_stmntItemProvider.dispose();
		if (else_stmntItemProvider != null) else_stmntItemProvider.dispose();
		if (break_stmntItemProvider != null) break_stmntItemProvider.dispose();
		if (goto_stmntItemProvider != null) goto_stmntItemProvider.dispose();
		if (print_stmntItemProvider != null) print_stmntItemProvider.dispose();
		if (assert_stmntItemProvider != null) assert_stmntItemProvider.dispose();
		if (c_codeItemProvider != null) c_codeItemProvider.dispose();
		if (c_exprItemProvider != null) c_exprItemProvider.dispose();
		if (c_declItemProvider != null) c_declItemProvider.dispose();
		if (c_trackItemProvider != null) c_trackItemProvider.dispose();
		if (c_stateItemProvider != null) c_stateItemProvider.dispose();
		if (optionsItemProvider != null) optionsItemProvider.dispose();
		if (bin_exprItemProvider != null) bin_exprItemProvider.dispose();
		if (un_exprItemProvider != null) un_exprItemProvider.dispose();
		if (cond_exprItemProvider != null) cond_exprItemProvider.dispose();
		if (len_exprItemProvider != null) len_exprItemProvider.dispose();
		if (timeout_exprItemProvider != null) timeout_exprItemProvider.dispose();
		if (np__exprItemProvider != null) np__exprItemProvider.dispose();
		if (enabled_exprItemProvider != null) enabled_exprItemProvider.dispose();
		if (pc_value_exprItemProvider != null) pc_value_exprItemProvider.dispose();
		if (name_exprItemProvider != null) name_exprItemProvider.dispose();
		if (run_exprItemProvider != null) run_exprItemProvider.dispose();
		if (andor_exprItemProvider != null) andor_exprItemProvider.dispose();
		if (chanpoll_exprItemProvider != null) chanpoll_exprItemProvider.dispose();
		if (num_constItemProvider != null) num_constItemProvider.dispose();
		if (enum_constItemProvider != null) enum_constItemProvider.dispose();
		if (mtype_constItemProvider != null) mtype_constItemProvider.dispose();
	}

}
