/*
* generated by Xtext
*/
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractTextualSlcoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TextualSlcoProposalProvider extends AbstractTextualSlcoProposalProvider {

}
